### ISSUE TITLE
How to set up "shouldOnlyDependsOn any golang standard library"

### ISSUE THREAD

**Issue by mucardoso** [fdaines/arch-go#10]
Hi, great library!
The only way I find is list all the dependencies, even the standard ones, example:

```
dependenciesRules:
  - package: "*.domain"
    shouldOnlyDependsOn:
      - "domain"
      - "errors" # why I need to mention the standard ones?
      - "time"   # why I need to mention the standard ones?
```

Thanks!
