### ISSUE TITLE
arch-go seem to ignore a rule

### ISSUE THREAD

**Issue by yoavsv** [fdaines/arch-go#2]
Hello,

I'm using the following configuration:

```yml
dependenciesRules:
  - package: ".package1.subackage1.subackage2"
    shouldNotDependsOn:
      - "**.hashicorp.**"
```

in `github.com/my-company/internal/package1/subackage1/subackage2` there's a file which imports 
`github.com/hashicorp/go-multierror` but the package passes the check.

Is it a bug?
