### ISSUE TITLE
Support for wildcard reference

### ISSUE THREAD

**Issue by matdurand** [fdaines/arch-go#21]
Hey, very nice project. I actually built a similar project (https://github.com/matdurand/go-import-checks), and I'm trying to see if I can deprecate it in favor of yours. But one thing I could do with mine is reference wildcards. 

The use-case goes like this. Let's say I have a "systems" package containing a bunch of "sub-systems" packages. I want to enforce that each subsystem is allowed to import anything from its own package and subpackages, but can only import the "api" package of another sub-system.

Here is the rules using "go-import-checks"
```
imports-checks:
  - folder: "internal/systems/$systemName"
    subpackages: true
    rules:
      - prefix: "github.com/matdurand/project1/"
        allow:
          - "internal/systems/$systemName/*"
          - "internal/systems/!$systemName/api"
          - "pkg/**"
```

instead of a wildcard, I'm using "$systemName", and are able to reference either "$systemName" or "!$systemName" in the rules. Does that make sense?

Maybe it could go like this with "go-arch"
```
 - package: "**.systems.$systemName.**"
    shouldOnlyDependsOn:
      internal:
        - "**.pkg.**"
        - "**.systems.$systemName.**"
    shouldNotDependsOn:
      internal:
        - "**.systems.!$systemName.**"
```

Is this something you think could be beneficial to go-arch?
