### ISSUE TITLE
Enhancement: Provide docker images and a Github Action to run arch-go

### ISSUE THREAD

**Issue by DGuhr** [fdaines/arch-go#24]
In short, I think this would be a neat tool in the CI/CD toolchain for go projects. Thus, it would be great to have a dockerized version of arch-go, and also a github action later on.

I started some PoC work on this on [this branch](https://github.com/DGuhr/arch-go/tree/dockerfile) on my fork.

So-far:
- it builds multiarch docker images and pushes them to quay.io [here](https://quay.io/repository/archgo/arch-go-test?tab=tags)

@fdaines fyi, and also a question / problem: I am a bit stuck now with a panic, trying to run the docker image (intel architecture) in the actual arch-go repo, mounting a volume with the repo to get the yaml file and the rest of the file.

example command to try it out: `docker run --rm -v `pwd`:`pwd` -w `pwd` quay.io/archgo/arch-go-test:latest`
This needs to run from the arch-go repos root folder (or: the folder where the config yml is, at the root of the repo) where the arch-go.yml resides. 
fyi:
`-v` mounts the current folder (`pwd`), `-w` sets the work directory inside the docker image. The image itself has arch-go in the [path](https://github.com/DGuhr/arch-go/blob/dockerfile/Dockerfile#L23), so it can be used elsewhere. 

I did the same locally running `go build .` and just moving the binary to `/usr/local/bin` and it worked like a charm, so now I am a bit out of ideas why this results in a panic :)

Screenshot: 

<img width="1673" alt="Screenshot 2023-04-15 at 19 13 06" src="https://user-images.githubusercontent.com/89905860/232242154-75b43c08-b347-4a59-985b-6d4d07f693d0.png">

I logged into the container and checked if all files are mounted correctly, and it seems they are (was a 1% chance because without finding the yml i get the expected error that no yml is found, and the yml is mounted), see 

<img width="1681" alt="Screenshot 2023-04-15 at 19 30 52" src="https://user-images.githubusercontent.com/89905860/232243954-437a5380-328e-4fc8-8aa6-53b3909e63e2.png">

so.. well, open for any ideas :)

**Comment by DGuhr** [comment]
ok so the root cause is: for some reason https://github.com/fdaines/arch-go/blob/master/internal/utils/packages/get_packages.go#L42 returns 0 packages when the directory is mounted. I am not entirely sure yet how it works entirely, may have sth to do with the go settings inside the container, and perhaps file systems rights on the package cache folder or sth. Will investigate further if I find the time, may be sth in the creation of the docker image :)

**Comment by DGuhr** [comment]
ok, creating some goenv packages ( /go and /.cache) and giving them 777 chmod helped. New version should be on shortly, which works in general, though I think there must be a better approach ;)

**Comment by fdaines** [comment]
I'm sorry @DGuhr , I cannot help with this issue until Tuesday because Im out of my home and without my computer.

**Comment by DGuhr** [comment]
@fdaines no problem at all, as said it is somehow solved for now :)

**Comment by DGuhr** [comment]
nvm, got it working, though I am not sure what I did is the idiomatic DSL usage ;)

draft PR for our usage with the docker image now here: https://github.com/RedHatInsights/authz/pull/89

**Comment by fdaines** [comment]
I believe that something like this should work

```
dependenciesRules: 
  - package: "**.domain.*"     
  shouldOnlyDependsOn: 
    internal: 
      - "**.contract.*"
    external: []
```

This would tell arch-go that domain package should only depends on an empty list of external packages, so then it should nhave no external dependencies.
You can replace the wildcards with the full package names

**Comment by DGuhr** [comment]
@fdaines tried it, but it gave me a "pass" when I introduced an external dependency, so I left it as is: https://github.com/RedHatInsights/authz/pull/89/files#diff-4bc06198f0eb26edf064adb2a72717423b8be44b18dd311d7a2078a0a8382bcdR6-R11

**Comment by fdaines** [comment]
@DGuhr , the following configuration seems to work:
```yaml
dependenciesRules:
  - package: "domain"
    shouldOnlyDependsOn:
      internal:
        - "domain"
    shouldNotDependsOn:
      external: [ ".**" ]
```

It would pass because `domain` package doesn't import any external package (test imports are excluded for this verification).

You can check that this works as expected changing to another packages, for example checking `api/http`.
```yaml
version: 1
threshold:
  compliance: 100
  coverage: 25
dependenciesRules:
  - package: "api/http"
    shouldOnlyDependsOn:
      internal:
        - "domain"
    shouldNotDependsOn:
      external: [ ".**" ]
```

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/5248484/232936883-bf72ea5b-c8ed-4010-a45a-7bf986c8a3ca.png">
